# Generated by Django 5.0.7 on 2024-07-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topsellsmodel',
            name='category',
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('new_price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorymodel')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.colormodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sizemodel')),
            ],
            options={
                'verbose_name': 'sell',
                'verbose_name_plural': 'sells',
            },
        ),
        migrations.DeleteModel(
            name='NewProductsModel',
        ),
        migrations.DeleteModel(
            name='TopSellsModel',
        ),
    ]
