# Generated by Django 5.0.7 on 2024-07-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_topsellsmodel_category_productsmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsmodel',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
